<?php

/**
 * Base_Agencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Agencia extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('agencia');
        $this->hasColumn('codigo', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}