<?php

/**
 * Base_CategoriasProductos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Categoria_id
 * @property integer $Producto_id
 * @property Categoria $Categoria
 * @property Producto $Producto
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_CategoriasProductos extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('categorias_productos');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Categoria_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('Producto_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categoria', array(
             'local' => 'Categoria_id',
             'foreign' => 'id'));

        $this->hasOne('Producto', array(
             'local' => 'Producto_id',
             'foreign' => 'id'));
    }
}