<?php

/**
 * Base_Categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Productos
 * @property Doctrine_Collection $CategoriasProductos
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Categoria extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('id', 'integer', 10, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('parent_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('nombre', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));


        $this->index('IX_Parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $this->index('IX_Nombre', array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Producto as Productos', array(
             'refClass' => 'CategoriasProductos',
             'local' => 'Categoria_id',
             'foreign' => 'Producto_id'));

        $this->hasMany('CategoriasProductos', array(
             'local' => 'id',
             'foreign' => 'Categoria_id'));
    }
}