<?php

/**
 * Base_Meta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $company
 * @property string $phone
 * @property integer $user_id
 * @property Users $Users
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Meta extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('meta');
        $this->hasColumn('id', 'integer', 8, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('first_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('company', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'unique' => true,
             'type' => 'integer',
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}