<?php

/**
 * Base_Producto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property date $vigencia
 * @property float $precio
 * @property Doctrine_Collection $Categorias
 * @property Doctrine_Collection $CategoriasProductos
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Producto extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('producto');
        $this->hasColumn('id', 'integer', 10, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('nombre', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('vigencia', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('precio', 'float', 5, array(
             'type' => 'float',
             'length' => '5',
             ));


        $this->index('IX_Nombre', array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Categoria as Categorias', array(
             'refClass' => 'CategoriasProductos',
             'local' => 'Producto_id',
             'foreign' => 'Categoria_id'));

        $this->hasMany('CategoriasProductos', array(
             'local' => 'id',
             'foreign' => 'Producto_id'));
    }
}