<?php

/**
 * Base_UserAutologin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $key_id
 * @property string $user_agent
 * @property string $last_ip
 * @property timestamp $last_login
 * @property integer $user_id
 * @property Users $Users
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_UserAutologin extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_autologin');
        $this->hasColumn('key_id', 'string', 32, array(
             'primary' => true,
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('user_agent', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '150',
             ));
        $this->hasColumn('last_ip', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}