<?php

/**
 * Base_Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ip_address
 * @property string $username
 * @property string $password
 * @property string $salt
 * @property string $email
 * @property string $activation_code
 * @property string $forgotten_password_code
 * @property string $remember_code
 * @property integer $created_on
 * @property integer $last_login
 * @property integer $active
 * @property integer $group_id
 * @property Groups $Groups
 * @property Doctrine_Collection $Meta
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Users extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', 8, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('ip_address', 'integer', 16, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '16',
             ));
        $this->hasColumn('username', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('password', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('salt', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('activation_code', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('forgotten_password_code', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('remember_code', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('created_on', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('last_login', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Groups', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasMany('Meta', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}