<?php

/**
 * Producto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Producto extends Base_Producto
{
    public function getAll()
    {
        return $this->getTable()->findAll()->toArray();
    }

    public function getProducto($id)
    {
        return $this->getTable()->findOneById($id);
    }
}